Application\AppBundle\Entity\AddressFormats:
    type: entity
    table: address_formats
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        addressformat:
            type: string
            length: 400
            fixed: false
            nullable: false
            column: addressFormat
    lifecycleCallbacks: {  }
