Application\AppBundle\Entity\AdminModules:
    type: entity
    table: admin_modules
    fields:
        id:
            id: true
            type: float
            nullable: false
            generator:
                strategy: IDENTITY
        adminmoduleparentid:
            type: float
            nullable: true
            column: adminModuleParentID
        adminmoduleurlkey:
            type: string
            length: 765
            fixed: false
            nullable: true
            column: adminModuleURLKey
        adminmoduleurlstring:
            type: string
            length: 765
            fixed: false
            nullable: true
            column: adminModuleURLString
        adminmodulestyleclass:
            type: string
            length: 765
            fixed: false
            nullable: true
            column: adminModuleStyleClass
        adminmodulestyleicon:
            type: string
            length: 765
            fixed: false
            nullable: true
            column: adminModuleStyleIcon
        adminmoduleorder:
            type: float
            nullable: true
            column: adminModuleOrder
        adminmoduletype:
            type: string
            length: null
            fixed: false
            nullable: true
            column: adminModuleType
        adminmodulestatus:
            type: string
            length: null
            fixed: false
            nullable: true
            column: adminModuleStatus
        adminmodulecaption:
            type: string
            length: 255
            fixed: false
            nullable: true
            column: adminModuleCaption
        adminmodulebreadcrumbcaption:
            type: string
            length: 255
            fixed: false
            nullable: true
            column: adminModuleBreadcrumbCaption
    lifecycleCallbacks: {  }
