Application\AppBundle\Entity\AffiliateWidgetSize:
    type: entity
    table: affiliate_widget_size
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        affiliatedealwidthpx:
            type: integer
            unsigned: false
            nullable: false
            column: affiliateDealWidthPx
        affiliatedealheightpx:
            type: integer
            unsigned: false
            nullable: false
            column: affiliateDealHeightPx
        widgetFormat:
            type: string
            length: null
            fixed: false
            nullable: false
            column: widget_format
        widgetscrolling:
            type: string
            length: null
            fixed: false
            nullable: false
            column: widgetScrolling
    lifecycleCallbacks: {  }
