Application\AppBundle\Entity\AffiliateCommissions:
    type: entity
    table: affiliate_commissions
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        affvisitorid:
            type: integer
            unsigned: false
            nullable: false
            column: affVisitorID
        affiliateuserid:
            type: integer
            unsigned: false
            nullable: false
            column: affiliateUserID
        actionid:
            type: integer
            unsigned: false
            nullable: false
            column: actionID
        commissionamount:
            type: decimal
            nullable: false
            column: commissionAmount
        commissionpercent:
            type: decimal
            nullable: false
            column: commissionPercent
        type:
            type: string
            length: null
            fixed: false
            nullable: false
        status:
            type: string
            length: null
            fixed: false
            nullable: false
        createddate:
            type: datetime
            nullable: false
            column: createdDate
        lastupdatedate:
            type: datetime
            nullable: false
            column: lastUpdateDate
        level:
            type: string
            length: null
            fixed: false
            nullable: false
    lifecycleCallbacks: {  }
