Application\AppBundle\Entity\AffiliateToSubscribers:
    type: entity
    table: affiliate_to_subscribers
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        bulkid:
            type: integer
            unsigned: false
            nullable: false
            column: bulkID
        subscemailid:
            type: string
            length: 150
            fixed: false
            nullable: false
            column: subscEmailID
        contactphone:
            type: string
            length: 50
            fixed: false
            nullable: false
            column: contactPhone
        confirmstatus:
            type: string
            length: null
            fixed: false
            nullable: false
            column: confirmStatus
        updateddate:
            type: datetime
            nullable: false
            column: updatedDate
    lifecycleCallbacks: {  }
