Application\AppBundle\Entity\AffiliatePayments:
    type: entity
    table: affiliate_payments
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        affiliateuserid:
            type: integer
            unsigned: false
            nullable: false
            column: affiliateUserID
        affiliatetransdate:
            type: datetime
            nullable: false
            column: affiliateTransDate
        affiliatetransamt:
            type: decimal
            nullable: false
            column: affiliateTransAmt
        affiliatetranstype:
            type: string
            length: 50
            fixed: false
            nullable: false
            column: affiliateTransType
        affiliatetransdescrption:
            type: string
            length: 255
            fixed: false
            nullable: true
            column: affiliateTransDescrption
        readstatus:
            type: string
            length: null
            fixed: false
            nullable: false
            column: readStatus
        transactiondescrforaffiliate:
            type: text
            nullable: false
            column: transactionDescrForAffiliate
    lifecycleCallbacks: {  }
