Application\AppBundle\Entity\AffiliateVisits:
    type: entity
    table: affiliate_visits
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        affiliateuserid:
            type: integer
            unsigned: false
            nullable: false
            column: affiliateUserID
        visitorid:
            type: integer
            unsigned: false
            nullable: false
            column: visitorID
        widgetid:
            type: integer
            unsigned: false
            nullable: false
            column: widgetID
        visittype:
            type: string
            length: null
            fixed: false
            nullable: false
            column: visitType
    lifecycleCallbacks: {  }
