Application\AppBundle\Entity\AffiliatePerformance:
    type: entity
    table: affiliate_performance
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        affvisitorid:
            type: integer
            unsigned: false
            nullable: false
            column: affVisitorID
        affiliateuserid:
            type: integer
            unsigned: false
            nullable: false
            column: affiliateUserID
        actionid:
            type: integer
            unsigned: false
            nullable: false
            column: actionID
        type:
            type: string
            length: null
            fixed: false
            nullable: false
        createddate:
            type: datetime
            nullable: false
            column: createdDate
    lifecycleCallbacks: {  }
