Application\AppBundle\Entity\AffiliateImportedUsers:
    type: entity
    table: affiliate_imported_users
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        bulkid:
            type: integer
            unsigned: false
            nullable: false
            column: bulkID
        useremail:
            type: string
            length: 150
            fixed: false
            nullable: false
            column: userEmail
        userpassword:
            type: string
            length: 255
            fixed: false
            nullable: false
            column: userPassword
        userfirstname:
            type: string
            length: 100
            fixed: false
            nullable: false
            column: userFirstName
        userlastname:
            type: string
            length: 100
            fixed: false
            nullable: false
            column: userLastName
        userphone:
            type: string
            length: 25
            fixed: false
            nullable: false
            column: userPhone
        usercity:
            type: string
            length: 100
            fixed: false
            nullable: false
            column: userCity
        useradress1:
            type: string
            length: 255
            fixed: false
            nullable: false
            column: userAdress1
        useradress2:
            type: string
            length: 255
            fixed: false
            nullable: false
            column: userAdress2
        userzip:
            type: string
            length: 12
            fixed: false
            nullable: false
            column: userZip
        userconfirm:
            type: string
            length: null
            fixed: false
            nullable: false
            column: userConfirm
        confirmdate:
            type: datetime
            nullable: false
            column: confirmDate
    lifecycleCallbacks: {  }
