Application\AppBundle\Entity\BusinessTypes:
    type: entity
    table: business_types
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        businesstypename:
            type: string
            length: 250
            fixed: false
            nullable: false
            column: businessTypeName
        businesstypedescription:
            type: text
            nullable: false
            column: businessTypeDescription
        businesstypeparent:
            type: integer
            unsigned: false
            nullable: false
            column: businessTypeParent
        businesstypestatus:
            type: string
            length: null
            fixed: false
            nullable: false
            column: businessTypeStatus
        businesstypesortorder:
            type: integer
            unsigned: false
            nullable: false
            column: businessTypeSortOrder
    lifecycleCallbacks: {  }
