Application\AppBundle\Entity\BusinessDealCampaigns:
    type: entity
    table: business_deal_campaigns
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        businessid:
            type: integer
            unsigned: false
            nullable: false
            column: businessID
        campaigndate:
            type: datetime
            nullable: false
            column: campaignDate
    manyToOne:
        dealid:
            targetEntity: Deals
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                dealID:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
