Application\AppBundle\Entity\BusinessTypeDetails:
    type: entity
    table: business_type_details
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        businesstypeid:
            type: integer
            unsigned: false
            nullable: false
            column: businessTypeID
        languageid:
            type: integer
            unsigned: false
            nullable: false
            column: languageID
        businesstypename:
            type: string
            length: 255
            fixed: false
            nullable: false
            column: businessTypeName
        businesstypedescription:
            type: text
            nullable: false
            column: businessTypeDescription
    lifecycleCallbacks: {  }
