Application\AppBundle\Entity\Business:
    type: entity
    table: business
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        businesslogin:
            type: string
            length: 100
            fixed: false
            nullable: false
            column: businessLogin
        businesspassword:
            type: string
            length: 50
            fixed: false
            nullable: false
            column: businessPassword
        businessname:
            type: string
            length: 100
            fixed: false
            nullable: false
            column: businessName
        businesskey:
            type: string
            length: 100
            fixed: false
            nullable: false
            column: businessKey
        businessaddress1:
            type: string
            length: 100
            fixed: false
            nullable: false
            column: businessAddress1
        businessaddress2:
            type: string
            length: 100
            fixed: false
            nullable: false
            column: businessAddress2
        businesscity:
            type: string
            length: 100
            fixed: false
            nullable: false
            column: businessCity
        businessstateprovince:
            type: string
            length: 100
            fixed: false
            nullable: false
            column: businessStateProvince
        businesslatitude:
            type: string
            length: 25
            fixed: false
            nullable: false
            column: businessLatitude
        businesslongitude:
            type: string
            length: 25
            fixed: false
            nullable: false
            column: businessLongitude
        businessprofile:
            type: text
            nullable: false
            column: businessProfile
        businesslogo:
            type: string
            length: 255
            fixed: false
            nullable: false
            column: businessLogo
        businesscfirstname:
            type: string
            length: 50
            fixed: false
            nullable: false
            column: businessCFirstName
        businessclastname:
            type: string
            length: 50
            fixed: false
            nullable: false
            column: businessCLastName
        businesscdesignation:
            type: string
            length: 100
            fixed: false
            nullable: false
            column: businessCDesignation
        businessphone:
            type: string
            length: 25
            fixed: false
            nullable: false
            column: businessPhone
        businessfax:
            type: string
            length: 25
            fixed: false
            nullable: false
            column: businessFax
        businesszip:
            type: string
            length: 10
            fixed: false
            nullable: false
            column: businessZip
        businessemail:
            type: string
            length: 100
            fixed: false
            nullable: false
            column: businessEmail
        businesswebsite:
            type: string
            length: 450
            fixed: false
            nullable: false
            column: businessWebsite
        businessaccountname:
            type: string
            length: 255
            fixed: false
            nullable: false
            column: businessAccountName
        businessaccounttype:
            type: string
            length: 100
            fixed: false
            nullable: false
            column: businessAccountType
        businessaccountdetails:
            type: text
            nullable: false
            column: businessAccountDetails
        businesspaypalemail:
            type: string
            length: 250
            fixed: false
            nullable: true
            column: businessPaypalEmail
        businessstatus:
            type: string
            length: null
            fixed: false
            nullable: false
            column: businessStatus
        businessaddeddate:
            type: datetime
            nullable: false
            column: businessAddedDate
        businessupdatedate:
            type: datetime
            nullable: false
            column: businessUpdateDate
        businessdefaultlanguageid:
            type: integer
            unsigned: false
            nullable: false
            column: businessDefaultLanguageID
    manyToOne:
        businesscountryid:
            targetEntity: Countries
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                businessCountryID:
                    referencedColumnName: id
            orphanRemoval: false
        businessstateid:
            targetEntity: States
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                businessStateID:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
