Application\AppBundle\Entity\BusinessLocations:
    type: entity
    table: business_locations
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        locname:
            type: string
            length: 100
            fixed: false
            nullable: false
            column: locName
        locaddress1:
            type: string
            length: 100
            fixed: false
            nullable: false
            column: locAddress1
        locaddress2:
            type: string
            length: 100
            fixed: false
            nullable: false
            column: locAddress2
        loccity:
            type: string
            length: 100
            fixed: false
            nullable: false
            column: locCity
        locstateid:
            type: integer
            unsigned: false
            nullable: false
            column: locStateID
        locprovince:
            type: string
            length: 100
            fixed: false
            nullable: false
            column: locProvince
        loccountryid:
            type: integer
            unsigned: false
            nullable: false
            column: locCountryID
        loczip:
            type: string
            length: 10
            fixed: false
            nullable: false
            column: locZip
        loclatitude:
            type: string
            length: 25
            fixed: false
            nullable: false
            column: locLatitude
        loclongitude:
            type: string
            length: 25
            fixed: false
            nullable: false
            column: locLongitude
        locphone:
            type: string
            length: 25
            fixed: false
            nullable: false
            column: locPhone
        locemail:
            type: string
            length: 50
            fixed: false
            nullable: false
            column: locEmail
        locstatus:
            type: string
            length: null
            fixed: false
            nullable: false
            column: locStatus
        loccreateddate:
            type: datetime
            nullable: false
            column: locCreatedDate
        locmodifieddate:
            type: datetime
            nullable: false
            column: locModifiedDate
    manyToOne:
        businessid:
            targetEntity: Business
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                businessID:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
