Application\AppBundle\Entity\CalendarCampaign:
    type: entity
    table: calendar_campaign
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        dealid:
            type: integer
            unsigned: false
            nullable: false
            column: dealID
        languageid:
            type: integer
            unsigned: false
            nullable: false
            column: languageID
        bannerdesignid:
            type: integer
            unsigned: false
            nullable: false
            column: bannerDesignID
        bannername:
            type: string
            length: 100
            fixed: false
            nullable: false
            column: bannerName
        campaignstartdate:
            type: date
            nullable: false
            column: campaignStartDate
        campaignenddate:
            type: date
            nullable: false
            column: campaignEndDate
        campaignstatus:
            type: string
            length: null
            fixed: false
            nullable: false
            column: campaignStatus
        campaignmodifieddate:
            type: datetime
            nullable: false
            column: campaignModifiedDate
        campaigncreateddate:
            type: datetime
            nullable: false
            column: campaignCreatedDate
        destinationurl:
            type: string
            length: 100
            fixed: false
            nullable: false
            column: destinationUrl
    lifecycleCallbacks: {  }
