Application\AppBundle\Entity\Campaigns:
    type: entity
    table: campaigns
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        thirdpartycampaignid:
            type: string
            length: 200
            fixed: false
            nullable: false
            column: thirdPartyCampaignID
        title:
            type: string
            length: 200
            fixed: false
            nullable: false
        createddate:
            type: datetime
            nullable: false
            column: createdDate
        scheduleddate:
            type: datetime
            nullable: false
            column: scheduledDate
        content:
            type: text
            nullable: false
        opencount:
            type: integer
            unsigned: false
            nullable: false
            column: openCount
        clickcount:
            type: integer
            unsigned: false
            nullable: false
            column: clickCount
        bouncecount:
            type: integer
            unsigned: false
            nullable: false
            column: bounceCount
        uniqueopenedcount:
            type: integer
            unsigned: false
            nullable: false
            column: uniqueOpenedCount
        uniqueclickcount:
            type: integer
            unsigned: false
            nullable: false
            column: uniqueClickCount
        unsubscribedcount:
            type: integer
            unsigned: false
            nullable: false
            column: unsubscribedCount
        forwardscount:
            type: integer
            unsigned: false
            nullable: false
            column: forwardsCount
        usercount:
            type: integer
            unsigned: false
            nullable: false
            column: userCount
        businessid:
            type: integer
            unsigned: false
            nullable: true
            column: businessID
    lifecycleCallbacks: {  }
