Application\AppBundle\Entity\CampaignRecipients:
    type: entity
    table: campaign_recipients
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        campaignid:
            type: integer
            unsigned: false
            nullable: false
            column: campaignID
        emailid:
            type: string
            length: 100
            fixed: false
            nullable: false
            column: emailID
        actiondate:
            type: datetime
            nullable: false
            column: actionDate
        type:
            type: string
            length: null
            fixed: false
            nullable: false
    lifecycleCallbacks: {  }
