Application\AppBundle\Entity\Charities:
    type: entity
    table: charities
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        charitytitle:
            type: string
            length: 100
            fixed: false
            nullable: false
            column: charityTitle
        charityaddress1:
            type: string
            length: 100
            fixed: false
            nullable: false
            column: charityAddress1
        charityaddress2:
            type: string
            length: 100
            fixed: false
            nullable: true
            column: charityAddress2
        charitycity:
            type: string
            length: 100
            fixed: false
            nullable: false
            column: charityCity
        stateid:
            type: integer
            unsigned: false
            nullable: false
            column: stateID
        charityprovince:
            type: string
            length: 100
            fixed: false
            nullable: true
            column: charityProvince
        countryid:
            type: integer
            unsigned: false
            nullable: false
            column: countryID
        charityzip:
            type: string
            length: 20
            fixed: false
            nullable: false
            column: charityZip
        charityphone:
            type: string
            length: 20
            fixed: false
            nullable: false
            column: charityPhone
        charityfax:
            type: string
            length: 20
            fixed: false
            nullable: false
            column: charityFax
        charityemail:
            type: string
            length: 100
            fixed: false
            nullable: false
            column: charityEmail
        charitywebsite:
            type: string
            length: 255
            fixed: false
            nullable: false
            column: charityWebsite
        charitydescription:
            type: text
            nullable: false
            column: charityDescription
        charitylogo:
            type: string
            length: 255
            fixed: false
            nullable: false
            column: charityLogo
        charityaccountname:
            type: string
            length: 100
            fixed: false
            nullable: false
            column: charityAccountName
        charityaccounttype:
            type: string
            length: 100
            fixed: false
            nullable: false
            column: charityAccountType
        charityaccountdetails:
            type: text
            nullable: false
            column: charityAccountDetails
        charitystatus:
            type: string
            length: null
            fixed: false
            nullable: false
            column: charityStatus
        charitycreateddate:
            type: datetime
            nullable: false
            column: CharityCreatedDate
        charityupdateddate:
            type: datetime
            nullable: false
            column: CharityUpdatedDate
    lifecycleCallbacks: {  }
