Application\AppBundle\Entity\Cities:
    type: entity
    table: cities
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        cityname:
            type: string
            length: 50
            fixed: false
            nullable: false
            column: cityName
        province:
            type: string
            length: 100
            fixed: false
            nullable: false
        citykeyid:
            type: string
            length: 100
            fixed: false
            nullable: false
            column: cityKeyID
        citylat:
            type: string
            length: 25
            fixed: false
            nullable: false
            column: cityLat
        citylng:
            type: string
            length: 25
            fixed: false
            nullable: false
            column: cityLng
        citylogoimage:
            type: string
            length: 250
            fixed: false
            nullable: false
            column: citylogoImage
        citybgimage:
            type: string
            length: 250
            fixed: false
            nullable: false
            column: citybgImage
        citystatus:
            type: string
            length: null
            fixed: false
            nullable: false
            column: cityStatus
        citycampaignlistid:
            type: string
            length: 255
            fixed: false
            nullable: true
            column: cityCampaignListID
    manyToOne:
        stateid:
            targetEntity: States
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                stateID:
                    referencedColumnName: id
            orphanRemoval: false
        countryid:
            targetEntity: Countries
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                countryID:
                    referencedColumnName: id
            orphanRemoval: false
        timezoneid:
            targetEntity: Timezones
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                timeZoneID:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
