Application\AppBundle\Entity\CityCharities:
    type: entity
    table: city_charities
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        cityid:
            type: integer
            unsigned: false
            nullable: false
            column: cityID
        charityid:
            type: integer
            unsigned: false
            nullable: false
            column: charityID
    lifecycleCallbacks: {  }
