Application\AppBundle\Entity\CmsSections:
    type: entity
    table: cms_sections
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        sectiontitle:
            type: string
            length: 100
            fixed: false
            nullable: false
            column: sectionTitle
        sectionstatus:
            type: string
            length: null
            fixed: false
            nullable: false
            column: sectionStatus
        sectiondefault:
            type: string
            length: null
            fixed: false
            nullable: false
            column: sectionDefault
        sectionpriority:
            type: integer
            unsigned: false
            nullable: false
            column: sectionPriority
    lifecycleCallbacks: {  }
