Application\AppBundle\Entity\ContentPages:
    type: entity
    table: content_pages
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        contenttitle:
            type: string
            length: 255
            fixed: false
            nullable: false
            column: contentTitle
        contentmenuname:
            type: string
            length: 100
            fixed: false
            nullable: false
            column: contentMenuName
        contentdescription:
            type: text
            nullable: false
            column: contentDescription
        contentmetatitle:
            type: string
            length: 255
            fixed: false
            nullable: false
            column: contentMetaTitle
        contentmetadescription:
            type: text
            nullable: false
            column: contentMetaDescription
        contentmetakeywords:
            type: text
            nullable: false
            column: contentMetaKeywords
        contentstatus:
            type: string
            length: null
            fixed: false
            nullable: false
            column: contentStatus
        contentcreateddate:
            type: datetime
            nullable: false
            column: contentCreatedDate
        contentisbasic:
            type: string
            length: null
            fixed: false
            nullable: false
            column: contentIsBasic
        contentisforsubpages:
            type: string
            length: null
            fixed: false
            nullable: true
            column: contentIsForSubPages
        contenturlkey:
            type: string
            length: 255
            fixed: false
            nullable: false
            column: contentUrlKey
        sectionid:
            type: integer
            unsigned: false
            nullable: false
            column: sectionID
        sortorder:
            type: integer
            unsigned: false
            nullable: false
            column: sortOrder
    lifecycleCallbacks: {  }
