Application\AppBundle\Entity\Countries:
    type: entity
    table: countries
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        countryname:
            type: string
            length: 100
            fixed: false
            nullable: false
            column: countryName
        countryavailable:
            type: string
            length: null
            fixed: false
            nullable: false
            column: countryAvailable
        countryisoa2:
            type: string
            length: 2
            fixed: true
            nullable: false
            column: countryIsoA2
        countryisoa3:
            type: string
            length: 3
            fixed: true
            nullable: false
            column: countryIsoA3
        countryisonumber:
            type: string
            length: 4
            fixed: false
            nullable: false
            column: countryIsoNumber
        countrypriority:
            type: integer
            unsigned: false
            nullable: false
            column: countryPriority
        addressformatid:
            type: integer
            unsigned: false
            nullable: false
            column: addressFormatID
    lifecycleCallbacks: {  }
