Application\AppBundle\Entity\Currencies:
    type: entity
    table: currencies
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        currencyname:
            type: string
            length: 50
            fixed: false
            nullable: false
            column: currencyName
        currencycode:
            type: string
            length: 4
            fixed: false
            nullable: false
            column: currencyCode
        currencysymbolleft:
            type: string
            length: 5
            fixed: false
            nullable: false
            column: currencySymbolLeft
        currencysymbolright:
            type: string
            length: 5
            fixed: false
            nullable: false
            column: currencySymbolRight
        currencydecimalplaces:
            type: integer
            unsigned: false
            nullable: false
            column: currencyDecimalPlaces
        currencyvalue:
            type: decimal
            nullable: false
            column: currencyValue
        currencydefault:
            type: string
            length: null
            fixed: false
            nullable: false
            column: currencyDefault
        currencytype:
            type: string
            length: null
            fixed: false
            nullable: false
            column: currencyType
        currencyactive:
            type: string
            length: null
            fixed: false
            nullable: false
            column: currencyActive
        currencystatus:
            type: string
            length: null
            fixed: false
            nullable: false
            column: currencyStatus
    lifecycleCallbacks: {  }
