Application\AppBundle\Entity\DealPriority:
    type: entity
    table: deal_priority
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        dealpriority:
            type: integer
            unsigned: false
            nullable: false
            column: dealPriority
    manyToOne:
        dealid:
            targetEntity: Deals
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                dealID:
                    referencedColumnName: id
            orphanRemoval: false
        cityid:
            targetEntity: Cities
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                cityID:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
