Application\AppBundle\Entity\DealRequests:
    type: entity
    table: deal_requests
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        dealrequestkey:
            type: string
            length: 255
            fixed: false
            nullable: false
            column: dealRequestKey
        dealrequestbusinesslocations:
            type: string
            length: 255
            fixed: false
            nullable: false
            column: dealRequestBusinessLocations
        dealrequesttimezone:
            type: integer
            unsigned: false
            nullable: false
            column: dealRequestTimeZone
        dealrequeststarttime:
            type: datetime
            nullable: false
            column: dealRequestStartTime
        dealrequestendtime:
            type: datetime
            nullable: false
            column: dealRequestEndTime
        dealrequestminbuylimit:
            type: integer
            unsigned: false
            nullable: false
            column: dealRequestMinBuyLimit
        dealrequestmaxbuylimit:
            type: integer
            unsigned: false
            nullable: true
            column: dealRequestMaxBuyLimit
        dealrequestminqntyreqtotipp:
            type: integer
            unsigned: false
            nullable: false
            column: dealRequestMinQntyReqToTipp
        dealrequestexpirydate:
            type: datetime
            nullable: true
            column: dealRequestExpiryDate
        dealrequestshownosbought:
            type: string
            length: null
            fixed: false
            nullable: false
            column: dealRequestShowNosBought
        dealrequestshowdealtipped:
            type: string
            length: null
            fixed: false
            nullable: false
            column: dealRequestShowDealTipped
        dealrequestonlineredemption:
            type: string
            length: null
            fixed: false
            nullable: false
            column: dealRequestOnlineRedemption
        dealrequestimage:
            type: string
            length: 255
            fixed: false
            nullable: false
            column: dealRequestImage
        dealrequestdate:
            type: datetime
            nullable: false
            column: dealRequestDate
        dealrequeststatus:
            type: string
            length: null
            fixed: false
            nullable: false
            column: dealRequestStatus
        dealrequestmaxgiftbuy:
            type: integer
            unsigned: false
            nullable: true
            column: dealRequestMaxGiftBuy
        shippingstatus:
            type: string
            length: null
            fixed: false
            nullable: false
            column: shippingStatus
        dealrequesttitle:
            type: string
            length: 255
            fixed: false
            nullable: false
            column: dealRequestTitle
        dealrequestcertificatetitle:
            type: string
            length: 255
            fixed: false
            nullable: false
            column: dealRequestCertificateTitle
        dealrequestfineprint:
            type: text
            nullable: false
            column: dealRequestFinePrint
        dealrequesthighlights:
            type: text
            nullable: false
            column: dealRequestHighlights
        dealrequestdescription:
            type: text
            nullable: false
            column: dealRequestDescription
        dealrequestreviews:
            type: text
            nullable: false
            column: dealRequestReviews
        dealrequestcertificateinstructions:
            type: text
            nullable: false
            column: dealRequestCertificateInstructions
    manyToOne:
        dealtypeid:
            targetEntity: DealTypes
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                dealTypeID:
                    referencedColumnName: id
            orphanRemoval: false
        businessid:
            targetEntity: Business
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                businessID:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
