Application\AppBundle\Entity\DealCertificates:
    type: entity
    table: deal_certificates
    fields:
        id:
            id: true
            type: bigint
            nullable: false
            generator:
                strategy: IDENTITY
        orderid:
            type: bigint
            nullable: false
            column: orderID
        orderitemid:
            type: bigint
            nullable: false
            column: orderItemID
        userid:
            type: integer
            unsigned: false
            nullable: false
            column: userID
        certificatecode:
            type: string
            length: 200
            fixed: false
            nullable: false
            column: certificateCode
        certificatename:
            type: string
            length: 200
            fixed: false
            nullable: false
            column: certificateName
        certificateemail:
            type: string
            length: 255
            fixed: false
            nullable: true
            column: certificateEmail
        cercreatedate:
            type: datetime
            nullable: false
            column: cerCreateDate
        cerexpirydate:
            type: datetime
            nullable: false
            column: cerExpiryDate
        statusUpdatedBy:
            type: string
            length: null
            fixed: false
            nullable: false
            column: status_updated_by
        statusUpdatedDate:
            type: datetime
            nullable: false
            column: status_updated_date
        cerstatus:
            type: string
            length: null
            fixed: false
            nullable: false
            column: cerStatus
        mailsendstatus:
            type: string
            length: null
            fixed: false
            nullable: false
            column: mailSendStatus
        mailsentby:
            type: string
            length: 127
            fixed: false
            nullable: false
            column: mailSentBy
        certificatedata:
            type: blob
            nullable: false
            column: certificateData
    manyToOne:
        dealid:
            targetEntity: Deals
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                dealID:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
