Application\AppBundle\Entity\DealCategories:
    type: entity
    table: deal_categories
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        dealcategoryname:
            type: string
            length: 255
            fixed: false
            nullable: false
            column: dealCategoryName
        dealcategorydescription:
            type: text
            nullable: false
            column: dealCategoryDescription
        dealcategorykey:
            type: string
            length: 200
            fixed: false
            nullable: false
            column: dealCategoryKey
        dealcategoryparent:
            type: integer
            unsigned: false
            nullable: false
            column: dealCategoryParent
        dealcategorystatus:
            type: string
            length: null
            fixed: false
            nullable: false
            column: dealCategoryStatus
        dealcategorysortorder:
            type: integer
            unsigned: false
            nullable: false
            column: dealCategorySortOrder
        dealcategoryimage:
            type: string
            length: 300
            fixed: false
            nullable: false
            column: dealCategoryImage
    lifecycleCallbacks: {  }
