Application\AppBundle\Entity\DealRequestLocations:
    type: entity
    table: deal_request_locations
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        locid:
            type: integer
            unsigned: false
            nullable: false
            column: locID
    manyToOne:
        dealrequestid:
            targetEntity: DealRequests
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                dealRequestID:
                    referencedColumnName: id
            orphanRemoval: false
        cityid:
            targetEntity: Cities
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                cityID:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
