Application\AppBundle\Entity\DealRequestOptions:
    type: entity
    table: deal_request_options
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        dealrequestoptionname:
            type: string
            length: 255
            fixed: false
            nullable: false
            column: dealRequestOptionName
        dealrequestoptioncerttitle:
            type: string
            length: 255
            fixed: false
            nullable: false
            column: dealRequestOptionCertTitle
        dealrequestoptionregularprice:
            type: decimal
            nullable: false
            column: dealRequestOptionRegularPrice
        dealrequestoptiondealprice:
            type: decimal
            nullable: false
            column: dealRequestOptionDealPrice
        dealrequestoptionquantity:
            type: integer
            unsigned: false
            nullable: false
            column: dealRequestOptionQuantity
        dealquantityunlimited:
            type: string
            length: null
            fixed: false
            nullable: false
            column: dealQuantityUnlimited
        dealrequestoptionstatus:
            type: string
            length: null
            fixed: false
            nullable: false
            column: dealRequestOptionStatus
        dealrequestoptiondefault:
            type: string
            length: null
            fixed: false
            nullable: false
            column: dealRequestOptionDefault
    manyToOne:
        dealrequestid:
            targetEntity: DealRequests
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                dealRequestID:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
