Application\AppBundle\Entity\DealTypes:
    type: entity
    table: deal_types
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        dealtypename:
            type: string
            length: 255
            fixed: false
            nullable: false
            column: dealTypeName
        dealtypedescription:
            type: text
            nullable: false
            column: dealTypeDescription
        paymentcollection:
            type: string
            length: null
            fixed: false
            nullable: false
            column: paymentCollection
        certficategenerate:
            type: string
            length: null
            fixed: false
            nullable: false
            column: certficateGenerate
        dealtypeposition:
            type: integer
            unsigned: false
            nullable: false
            column: dealTypePosition
        dealtypestatus:
            type: string
            length: null
            fixed: false
            nullable: false
            column: dealTypeStatus
        isfeatured:
            type: string
            length: null
            fixed: false
            nullable: false
            column: isFeatured
        featuredlink:
            type: integer
            unsigned: false
            nullable: true
            column: featuredLink
        dealtypekey:
            type: string
            length: 40
            fixed: false
            nullable: false
            column: dealTypeKey
        lockedstatus:
            type: string
            length: null
            fixed: false
            nullable: false
            column: lockedStatus
    lifecycleCallbacks: {  }
