Application\AppBundle\Entity\DealToCategory:
    type: entity
    table: deal_to_category
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
    manyToOne:
        dealcategoryid:
            targetEntity: DealCategories
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                dealCategoryID:
                    referencedColumnName: id
            orphanRemoval: false
        dealid:
            targetEntity: Deals
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                dealID:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
