Application\AppBundle\Entity\DealReviews:
    type: entity
    table: deal_reviews
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        languageid:
            type: integer
            unsigned: false
            nullable: false
            column: languageID
        reviewtext:
            type: text
            nullable: false
            column: reviewText
        reviweddate:
            type: datetime
            nullable: false
            column: reviwedDate
        reviewstatus:
            type: string
            length: null
            fixed: false
            nullable: false
            column: reviewStatus
        updateddate:
            type: datetime
            nullable: false
            column: updatedDate
        approvedby:
            type: integer
            unsigned: false
            nullable: false
            column: approvedBy
        reviewfollow:
            type: string
            length: null
            fixed: false
            nullable: false
            column: reviewFollow
    manyToOne:
        userid:
            targetEntity: Users
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                userID:
                    referencedColumnName: id
            orphanRemoval: false
        dealid:
            targetEntity: Deals
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                dealID:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
