Application\AppBundle\Entity\DealImages:
    type: entity
    table: deal_images
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        dealimage:
            type: string
            length: 255
            fixed: false
            nullable: false
            column: dealImage
        dealimagepriority:
            type: integer
            unsigned: false
            nullable: false
            column: dealImagePriority
        dealimagestatus:
            type: string
            length: null
            fixed: false
            nullable: false
            column: dealImageStatus
    manyToOne:
        dealid:
            targetEntity: Deals
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                dealID:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
