Application\AppBundle\Entity\DealRequestToCategory:
    type: entity
    table: deal_request_to_category
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        dealtocategoryid:
            type: integer
            unsigned: false
            nullable: false
            column: dealToCategoryID
        dealid:
            type: integer
            unsigned: false
            nullable: false
            column: dealID
        dealcategoryid:
            type: integer
            unsigned: false
            nullable: false
            column: dealCategoryID
    lifecycleCallbacks: {  }
