Application\AppBundle\Entity\DealRequestImages:
    type: entity
    table: deal_request_images
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        dealrequestid:
            type: integer
            unsigned: false
            nullable: false
            column: dealRequestID
        dealrequestimage:
            type: string
            length: 255
            fixed: false
            nullable: false
            column: dealRequestImage
        dealrequestmagepriority:
            type: integer
            unsigned: false
            nullable: false
            column: dealRequestmagePriority
        dealrequestimagestatus:
            type: string
            length: null
            fixed: false
            nullable: false
            column: dealRequestImageStatus
    lifecycleCallbacks: {  }
