Application\AppBundle\Entity\DealCampaigns:
    type: entity
    table: deal_campaigns
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        dealid:
            type: integer
            unsigned: false
            nullable: false
            column: dealID
        cityid:
            type: integer
            unsigned: false
            nullable: false
            column: cityID
        dealtypekey:
            type: string
            length: 50
            fixed: false
            nullable: false
            column: dealTypeKey
        insertdate:
            type: datetime
            nullable: false
            column: insertDate
        campaigndate:
            type: datetime
            nullable: false
            column: campaignDate
    lifecycleCallbacks: {  }
