Application\AppBundle\Entity\DiscountsPromo:
    type: entity
    table: discounts_promo
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        promoname:
            type: string
            length: 200
            fixed: false
            nullable: false
            column: promoName
        promodescription:
            type: text
            nullable: false
            column: promoDescription
        promocode:
            type: string
            length: 20
            fixed: false
            nullable: false
            column: promoCode
        promodiscount:
            type: float
            nullable: false
            column: promoDiscount
        promodiscounttype:
            type: string
            length: null
            fixed: false
            nullable: false
            column: promoDiscountType
        promominorderamount:
            type: float
            nullable: false
            column: promoMinOrderAmount
        promomaxusage:
            type: integer
            unsigned: false
            nullable: false
            column: promoMaxUsage
        promomaxusageperuser:
            type: integer
            unsigned: false
            nullable: false
            column: promoMaxUsagePerUser
        promoeffectondeals:
            type: string
            length: null
            fixed: false
            nullable: false
            column: promoEffectOnDeals
        promostartdate:
            type: date
            nullable: false
            column: promoStartDate
        promoexpdate:
            type: date
            nullable: false
            column: promoExpDate
        promostatus:
            type: string
            length: null
            fixed: false
            nullable: false
            column: promoStatus
        promoaddedtime:
            type: datetime
            nullable: false
            column: promoAddedTime
    manyToOne:
        dealid:
            targetEntity: Deals
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                DealID:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
