Application\AppBundle\Entity\EmailTemplate:
    type: entity
    table: email_template
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        emailfromname:
            type: string
            length: 200
            fixed: false
            nullable: false
            column: emailFromName
        emailfromemail:
            type: string
            length: 200
            fixed: false
            nullable: false
            column: emailFromEmail
        emailtemplatename:
            type: string
            length: 255
            fixed: false
            nullable: false
            column: emailTemplateName
        emailsendtokey:
            type: string
            length: 100
            fixed: false
            nullable: false
            column: emailSendToKey
        emailsubject:
            type: string
            length: 255
            fixed: false
            nullable: false
            column: emailSubject
        emailhtml:
            type: text
            nullable: false
            column: emailHtml
        emailtext:
            type: text
            nullable: true
            column: emailText
        editable:
            type: string
            length: null
            fixed: false
            nullable: false
    lifecycleCallbacks: {  }
