Application\AppBundle\Entity\GeozoneToRegions:
    type: entity
    table: geozone_to_regions
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
    manyToOne:
        geozoneid:
            targetEntity: Geozones
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                geoZoneID:
                    referencedColumnName: id
            orphanRemoval: false
        stateid:
            targetEntity: States
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                StateID:
                    referencedColumnName: id
            orphanRemoval: false
        countryid:
            targetEntity: Countries
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                countryID:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
