Application\AppBundle\Entity\Geozones:
    type: entity
    table: geozones
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        geozonename:
            type: string
            length: 200
            fixed: false
            nullable: false
            column: geoZoneName
        geozonedescription:
            type: string
            length: 200
            fixed: false
            nullable: false
            column: geoZoneDescription
        geozoneadded:
            type: datetime
            nullable: false
            column: geoZoneAdded
        geozonemodified:
            type: datetime
            nullable: false
            column: geoZoneModified
        geozonestatus:
            type: string
            length: null
            fixed: false
            nullable: false
            column: geoZoneStatus
    lifecycleCallbacks: {  }
