Application\AppBundle\Entity\Languages:
    type: entity
    table: languages
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        languagename:
            type: string
            length: 32
            fixed: false
            nullable: false
            column: languageName
        languagecode:
            type: string
            length: 4
            fixed: false
            nullable: false
            column: languageCode
        languagelcidstring:
            type: string
            length: 5
            fixed: false
            nullable: false
            column: LanguageLCIDstring
        languagelocale:
            type: string
            length: 255
            fixed: false
            nullable: false
            column: languageLocale
        languageimage:
            type: string
            length: 64
            fixed: false
            nullable: false
            column: languageImage
        languagesortorder:
            type: integer
            unsigned: false
            nullable: false
            column: languageSortOrder
        languagestatus:
            type: string
            length: null
            fixed: false
            nullable: false
            column: languageStatus
        languagedefault:
            type: string
            length: null
            fixed: false
            nullable: false
            column: languageDefault
    lifecycleCallbacks: {  }
