Application\AppBundle\Entity\NetpayPaymentMethods:
    type: entity
    table: netpay_payment_methods
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        methodcode:
            type: string
            length: 50
            fixed: false
            nullable: false
            column: methodCode
        methodname:
            type: string
            length: 100
            fixed: false
            nullable: false
            column: methodName
        bank:
            type: string
            length: null
            fixed: false
            nullable: false
            column: Bank
        status:
            type: string
            length: null
            fixed: false
            nullable: false
    lifecycleCallbacks: {  }
