Application\AppBundle\Entity\Newsletters:
    type: entity
    table: newsletters
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        newsletterfromname:
            type: string
            length: 200
            fixed: false
            nullable: false
            column: newsletterFromName
        newsletterfromemail:
            type: string
            length: 200
            fixed: false
            nullable: false
            column: newsletterFromEmail
        newslettersubject:
            type: string
            length: 255
            fixed: false
            nullable: false
            column: newsLetterSubject
        newslettercontenthtml:
            type: text
            nullable: false
            column: newsLetterContentHtml
        newslettercontenttext:
            type: text
            nullable: false
            column: newsLetterContentText
        newslettersent:
            type: string
            length: null
            fixed: false
            nullable: false
            column: newsletterSent
        newslettercreatedate:
            type: datetime
            nullable: false
            column: newsletterCreateDate
        newslettersentdate:
            type: datetime
            nullable: true
            column: newsletterSentDate
    lifecycleCallbacks: {  }
