Application\AppBundle\Entity\OrderItems:
    type: entity
    table: order_items
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        orderitemprice:
            type: decimal
            nullable: false
            column: orderItemPrice
        orderitemquantity:
            type: integer
            unsigned: false
            nullable: false
            column: orderItemQuantity
        orderitemsubtotal:
            type: decimal
            nullable: false
            column: orderItemSubtotal
        istaxable:
            type: string
            length: null
            fixed: false
            nullable: false
            column: isTaxable
        orderitemtaxrate:
            type: decimal
            nullable: true
            column: orderItemTaxRate
        orderitemtaxdescription:
            type: text
            nullable: true
            column: orderItemTaxDescription
        ordergiveasgift:
            type: string
            length: null
            fixed: false
            nullable: false
            column: orderGiveAsGift
        certificatename:
            type: string
            length: 200
            fixed: false
            nullable: true
            column: certificateName
        certificateemail:
            type: string
            length: 200
            fixed: false
            nullable: true
            column: certificateEmail
        dealoptionname:
            type: string
            length: 511
            fixed: false
            nullable: false
            column: dealOptionName
        dealoptioncerttitle:
            type: string
            length: 511
            fixed: false
            nullable: false
            column: dealOptionCertTitle
        addedtime:
            type: datetime
            nullable: false
            column: addedTime
        redeemslotid:
            type: integer
            unsigned: false
            nullable: false
            column: redeemSlotID
    manyToOne:
        dealid:
            targetEntity: Deals
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                dealID:
                    referencedColumnName: id
            orphanRemoval: false
        dealoptionid:
            targetEntity: DealOptions
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                dealOptionID:
                    referencedColumnName: id
            orphanRemoval: false
        orderid:
            targetEntity: Orders
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                orderID:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
