Application\AppBundle\Entity\Orders:
    type: entity
    table: orders
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        ordernumber:
            type: bigint
            nullable: false
            column: orderNumber
        orderstatus:
            type: string
            length: null
            fixed: false
            nullable: false
            column: orderStatus
        ordertype:
            type: string
            length: null
            fixed: false
            nullable: false
            column: orderType
        dealtype:
            type: string
            length: null
            fixed: false
            nullable: false
            column: dealType
        ordercreateddate:
            type: datetime
            nullable: false
            column: orderCreatedDate
        orderstatusdate:
            type: datetime
            nullable: false
            column: orderStatusDate
        languageid:
            type: integer
            unsigned: false
            nullable: true
            column: languageID
        ordersubtotal:
            type: decimal
            nullable: false
            column: orderSubtotal
        orderpromocode:
            type: string
            length: 20
            fixed: false
            nullable: true
            column: orderPromoCode
        orderpromodiscountamount:
            type: decimal
            nullable: true
            column: orderPromoDiscountAmount
        orderusercreditamount:
            type: decimal
            nullable: false
            column: orderUserCreditAmount
        paymentsettingsgroupid:
            type: integer
            unsigned: false
            nullable: true
            column: paymentSettingsGroupID
        orderpaymentmethodname:
            type: string
            length: 200
            fixed: false
            nullable: false
            column: orderPaymentMethodName
        paymenttype:
            type: string
            length: null
            fixed: false
            nullable: false
            column: paymentType
        paymentstatus:
            type: string
            length: null
            fixed: false
            nullable: false
            column: paymentStatus
        transactionid:
            type: text
            nullable: true
            column: transactionID
        orderqty:
            type: integer
            unsigned: false
            nullable: false
            column: orderQty
        ordertaxamount:
            type: decimal
            nullable: true
            column: orderTaxAmount
        ordercharityid:
            type: integer
            unsigned: false
            nullable: true
            column: orderCharityID
        ordercharityamount:
            type: decimal
            nullable: true
            column: orderCharityAmount
        ordercommissionamount:
            type: decimal
            nullable: true
            column: orderCommissionAmount
        orderpaymentgatewaycharge:
            type: decimal
            nullable: true
            column: orderPaymentGatewayCharge
        orderotherservicecharge:
            type: decimal
            nullable: true
            column: orderOtherServiceCharge
        ordertotalamount:
            type: decimal
            nullable: false
            column: orderTotalAmount
        billingfirstname:
            type: string
            length: 200
            fixed: false
            nullable: false
            column: billingFirstName
        billinglastname:
            type: string
            length: 200
            fixed: false
            nullable: true
            column: billingLastName
        billingaddress1:
            type: string
            length: 200
            fixed: false
            nullable: false
            column: billingAddress1
        billingaddress2:
            type: string
            length: 200
            fixed: false
            nullable: true
            column: billingAddress2
        billingcity:
            type: string
            length: 200
            fixed: false
            nullable: false
            column: billingCity
        billingstate:
            type: integer
            unsigned: false
            nullable: false
            column: billingState
        billingprovince:
            type: string
            length: 200
            fixed: false
            nullable: true
            column: billingProvince
        billingcountry:
            type: integer
            unsigned: false
            nullable: false
            column: billingCountry
        billingzip:
            type: string
            length: 50
            fixed: false
            nullable: true
            column: billingZip
        billingphone:
            type: string
            length: 25
            fixed: false
            nullable: false
            column: billingPhone
        billingemail:
            type: string
            length: 100
            fixed: false
            nullable: false
            column: billingEmail
        carddata:
            type: text
            nullable: true
            column: cardData
        orderremoved:
            type: string
            length: null
            fixed: false
            nullable: false
            column: orderRemoved
        purchasedcurrency:
            type: string
            length: 5
            fixed: false
            nullable: true
            column: purchasedCurrency
        shippingamount:
            type: float
            nullable: false
            column: shippingAmount
        shipmentstatus:
            type: string
            length: null
            fixed: false
            nullable: false
            column: shipmentStatus
        shipmentdate:
            type: datetime
            nullable: false
            column: shipmentDate
        carrierdetails:
            type: text
            nullable: false
            column: carrierDetails
        paymentnotes:
            type: text
            nullable: false
            column: paymentNotes
        netpayorderid:
            type: string
            length: 20
            fixed: false
            nullable: false
            column: netpayOrderID
        netpaypaymenttype:
            type: string
            length: 5
            fixed: false
            nullable: false
            column: netpayPaymentType
        orderhold:
            type: string
            length: null
            fixed: false
            nullable: false
            column: orderHold
    manyToOne:
        cityid:
            targetEntity: Cities
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                cityID:
                    referencedColumnName: id
            orphanRemoval: false
        userid:
            targetEntity: Users
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                userID:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
