Application\AppBundle\Entity\PaymentTransactions:
    type: entity
    table: payment_transactions
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        transactionid:
            type: text
            nullable: true
            column: transactionID
        orderid:
            type: integer
            unsigned: false
            nullable: false
            column: orderID
        userid:
            type: integer
            unsigned: false
            nullable: false
            column: userID
        completeddate:
            type: datetime
            nullable: false
            column: completedDate
        extra:
            type: text
            nullable: true
        paymenttype:
            type: string
            length: 100
            fixed: false
            nullable: true
            column: paymentType
        paymentgateway:
            type: string
            length: 100
            fixed: false
            nullable: true
            column: paymentGateway
        paymentresponse:
            type: text
            nullable: true
            column: paymentResponse
        ordersubtotal:
            type: decimal
            nullable: true
            column: orderSubTotal
        ordertotal:
            type: decimal
            nullable: true
            column: orderTotal
        taxamount:
            type: decimal
            nullable: true
            column: taxAmount
    lifecycleCallbacks: {  }
