Application\AppBundle\Entity\PaymentSettingsGroup:
    type: entity
    table: payment_settings_group
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        paysetgrouplabel:
            type: string
            length: 255
            fixed: false
            nullable: false
            column: paySetGroupLabel
        paysetgroupkey:
            type: string
            length: 255
            fixed: false
            nullable: false
            column: paySetGroupKey
        paysetgroupsortorder:
            type: integer
            unsigned: false
            nullable: false
            column: paySetGroupSortOrder
        paysetgroupstatus:
            type: string
            length: null
            fixed: false
            nullable: false
            column: paySetGroupStatus
        paytsetgrouplastupdated:
            type: datetime
            nullable: false
            column: paytSetGroupLastUpdated
    lifecycleCallbacks: {  }
