Application\AppBundle\Entity\PromotionalBanners:
    type: entity
    table: promotional_banners
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        bannercaption:
            type: string
            length: 255
            fixed: false
            nullable: true
            column: bannerCaption
        bannerdisplaytype:
            type: string
            length: null
            fixed: false
            nullable: false
            column: bannerDisplayType
        bannerscript:
            type: text
            nullable: false
            column: bannerScript
        bannerimage:
            type: string
            length: 200
            fixed: false
            nullable: false
            column: bannerImage
        bannerswf:
            type: string
            length: 200
            fixed: false
            nullable: false
            column: bannerSwf
        bannerurl:
            type: string
            length: 200
            fixed: false
            nullable: false
            column: bannerURL
        bannerstatus:
            type: string
            length: null
            fixed: false
            nullable: false
            column: bannerStatus
        bannercreateddate:
            type: datetime
            nullable: false
            column: bannerCreatedDate
    manyToOne:
        bannertypeid:
            targetEntity: PromotionalBannersType
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                bannerTypeID:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
