Application\AppBundle\Entity\PromotionalBannersType:
    type: entity
    table: promotional_banners_type
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        bannertypeposition:
            type: string
            length: 200
            fixed: false
            nullable: false
            column: bannerTypePosition
        bannertypewidth:
            type: integer
            unsigned: false
            nullable: false
            column: bannerTypeWidth
        bannertypeheight:
            type: integer
            unsigned: false
            nullable: false
            column: bannerTypeHeight
        bannertypestatus:
            type: string
            length: null
            fixed: false
            nullable: false
            column: bannerTypeStatus
    lifecycleCallbacks: {  }
