Application\AppBundle\Entity\RefundTransactions:
    type: entity
    table: refund_transactions
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        transactionid:
            type: text
            nullable: true
            column: transactionID
        orderid:
            type: integer
            unsigned: false
            nullable: false
            column: orderID
        dealid:
            type: integer
            unsigned: false
            nullable: false
            column: dealID
        userid:
            type: integer
            unsigned: false
            nullable: false
            column: userID
        completeddate:
            type: datetime
            nullable: false
            column: completedDate
        refundtype:
            type: string
            length: 100
            fixed: false
            nullable: true
            column: refundType
        refundgateway:
            type: string
            length: 100
            fixed: false
            nullable: true
            column: refundGateway
        refundresponse:
            type: text
            nullable: true
            column: refundResponse
        refundamount:
            type: decimal
            nullable: true
            column: refundAmount
        refundexecutionid:
            type: integer
            unsigned: false
            nullable: false
            column: refundExecutionID
    lifecycleCallbacks: {  }
