Application\AppBundle\Entity\SearchEngine:
    type: entity
    table: search_engine
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        searchenginename:
            type: string
            length: 225
            fixed: false
            nullable: false
            column: searchEngineName
        searchengineurl:
            type: string
            length: 225
            fixed: false
            nullable: false
            column: searchEngineURL
        searchparameter:
            type: string
            length: 25
            fixed: false
            nullable: false
            column: searchParameter
    lifecycleCallbacks: {  }
