Application\AppBundle\Entity\Subscribers:
    type: entity
    table: subscribers
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        subscemailid:
            type: string
            length: 255
            fixed: false
            nullable: false
            column: subscEmailID
        contactphone:
            type: string
            length: 20
            fixed: false
            nullable: false
            column: contactPhone
    manyToOne:
        userid:
            targetEntity: Users
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                userID:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
