Application\AppBundle\Entity\TaxClasses:
    type: entity
    table: tax_classes
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        taxclassname:
            type: string
            length: 120
            fixed: false
            nullable: false
            column: taxClassName
        taxclassdescription:
            type: string
            length: 200
            fixed: false
            nullable: false
            column: taxClassDescription
        taxclassstatus:
            type: string
            length: null
            fixed: false
            nullable: false
            column: taxClassStatus
    lifecycleCallbacks: {  }
