Application\AppBundle\Entity\TaxRates:
    type: entity
    table: tax_rates
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        taxrate:
            type: decimal
            nullable: false
            column: taxRate
        taxpriority:
            type: integer
            unsigned: false
            nullable: false
            column: taxPriority
        taxdescription:
            type: string
            length: 50
            fixed: false
            nullable: false
            column: taxDescription
    manyToOne:
        taxclassid:
            targetEntity: TaxClasses
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                taxClassID:
                    referencedColumnName: id
            orphanRemoval: false
        geozoneid:
            targetEntity: Geozones
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                geoZoneID:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
