Application\AppBundle\Entity\UsersFollowCategory:
    type: entity
    table: users_follow_category
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
    manyToOne:
        userid:
            targetEntity: Users
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                userID:
                    referencedColumnName: id
            orphanRemoval: false
        dealcategoryid:
            targetEntity: DealCategories
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                dealCategoryID:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
