Application\AppBundle\Entity\UserApi:
    type: entity
    table: user_api
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        userapikey:
            type: string
            length: 105
            fixed: false
            nullable: false
            column: userApiKey
        apikeytitle:
            type: string
            length: 200
            fixed: false
            nullable: false
            column: apiKeyTitle
        apiusertype:
            type: string
            length: null
            fixed: false
            nullable: false
            column: apiUserType
        apiuserstatus:
            type: string
            length: null
            fixed: false
            nullable: false
            column: apiUserStatus
        apiusercreateddate:
            type: datetime
            nullable: false
            column: apiUserCreatedDate
    manyToOne:
        userid:
            targetEntity: Users
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                userID:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
