Application\AppBundle\Entity\UserPrivilageCity:
    type: entity
    table: user_privilage_city
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
    manyToOne:
        adminuserid:
            targetEntity: AdminUsers
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                adminuserID:
                    referencedColumnName: id
            orphanRemoval: false
        cityid:
            targetEntity: Cities
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                cityID:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
