Application\AppBundle\Entity\UserTransactionOrders:
    type: entity
    table: user_transaction_orders
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
    manyToOne:
        orderid:
            targetEntity: Orders
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                orderID:
                    referencedColumnName: id
            orphanRemoval: false
        usertransactionid:
            targetEntity: UsersTransactions
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                userTransactionID:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
