Application\AppBundle\Entity\UsersTransactions:
    type: entity
    table: users_transactions
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        transactiontype:
            type: string
            length: null
            fixed: false
            nullable: false
            column: transactionType
        transactiondate:
            type: datetime
            nullable: false
            column: transactionDate
        transactionamount:
            type: decimal
            nullable: false
            column: transactionAmount
        transactiondescription:
            type: text
            nullable: true
            column: transactionDescription
        transactionstatus:
            type: string
            length: null
            fixed: false
            nullable: false
            column: transactionStatus
    manyToOne:
        userid:
            targetEntity: Users
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                userID:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
