Application\AppBundle\Entity\UsersCcInfo:
    type: entity
    table: users_cc_info
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        nameoncard:
            type: string
            length: 200
            fixed: false
            nullable: false
            column: nameonCard
        cardtype:
            type: string
            length: 100
            fixed: false
            nullable: false
            column: cardType
        cardnumber:
            type: string
            length: 500
            fixed: false
            nullable: false
            column: cardNumber
        expmonth:
            type: boolean
            nullable: false
            column: expMonth
        expyear:
            type: integer
            unsigned: false
            nullable: false
            column: expYear
        addeddate:
            type: datetime
            nullable: false
            column: addedDate
        securitycode:
            type: string
            length: 4
            fixed: false
            nullable: false
            column: securityCode
    manyToOne:
        userid:
            targetEntity: Users
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                userID:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
