Application\AppBundle\Entity\VisitorCountInfo:
    type: entity
    table: visitor_count_info
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        date:
            type: date
            nullable: false
        newvisitorcount:
            type: integer
            unsigned: false
            nullable: false
            column: newVisitorCount
        returningvisitorcount:
            type: integer
            unsigned: false
            nullable: false
            column: returningVisitorCount
        returningvisitcount:
            type: integer
            unsigned: false
            nullable: false
            column: returningVisitCount
        totalvisitcount:
            type: integer
            unsigned: false
            nullable: false
            column: totalVisitCount
    lifecycleCallbacks: {  }
