Application\AppBundle\Entity\VisitorUrlLog:
    type: entity
    table: visitor_url_log
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        visitorid:
            type: integer
            unsigned: false
            nullable: false
            column: visitorID
        currenturl:
            type: string
            length: 765
            fixed: false
            nullable: false
            column: currentUrl
        refererurl:
            type: string
            length: 765
            fixed: false
            nullable: false
            column: refererUrl
        visittime:
            type: datetime
            nullable: false
            column: visitTime
    lifecycleCallbacks: {  }
